### ISSUE TITLE
No SSL in Native Build

### ISSUE THREAD

**Issue by deeperunderstanding** [micronaut-projects/micronaut-jms#205]
### Expected Behavior

Configuring a connection string like follows should resolve the correct transport mechanism.

```yaml
micronaut:
  jms:
    activemq:
      classic:
        enabled: true
        connection-string: 'ssl://localhost:61616'
```

### Actual Behaviour

When building a native docker image with the "dockerBuildNative" gradle task the following errpr occurs on application startup, when attempting to create the AMQConnectionFactory: Transport scheme NOT recognized: [ssl]
The problem does not occur in JVM builds.

### Version

3.2.4
